### PR TITLE
samplePlayer amp fix & multichannel rel fix

### PR DESCRIPTION
**Pull request by thresholdpeople**
This is for issue #24.

### CODE REVIEW

**Comment by thresholdpeople** [comment]
this also now has a fix for #25

**Comment by danielmkarlsson** [comment]
Woot, woot!

**Comment by danielmkarlsson** [comment]
I dunno about the release tho?
Try this and see what you make of it:

```
(
Pdef(0,
	Pbind(*[
		type: \cln,
		snd: \mmd,
		dur: 1/8,
		num: (0 .. 12),
		amp: Pclump(13, Plprand(0.0, 1/59)),
		pan: Pclump(13, Pwhite(0.0, 1.0)),
		rel: Pclump(13, Plprand(0.0, 0.0000000001)),
		crv: Pclump(13, Pwhite(-8.0, 8.0)),
	])
).play
)
```

**Comment by thresholdpeople** [comment]
Seems to be working for me? Or are you getting a boolean error?

**Comment by danielmkarlsson** [comment]
Sorry, I should have wrot that on my machine the release is unchanged at default.

**Comment by thresholdpeople** [comment]
Sorry, still not sure I follow - are you expecting the sounds to stop sustaining due to short release times?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by danielmkarlsson** [comment]
Again, I'm sorry for lack of pertinent information. I was expecting the release times to get short at least sometimes. On my machine they seem to be unaffected, by anything at all, when multichannel expanded.

**Comment by thresholdpeople** [comment]
Ahh yep, I thought the original behavior of the sampler was that samples play through to the end unless legato or sustain are below 1... I had to do extra things to make them play like this!

Ahh, though in the previous version the envelope was separate from the samplePlayer and would only kick in if called explicitly. Right. There should be a way to get this sort of behavior without too much trouble.

The env I used is Env.linen, and I set the hold time to be the length of the sample, scalable by timeScale. A fix, though not perfect, would be to swap in an Env.perc, and place the holdTime variable (renamed as release, with the release arg also acting as a scaler) as the release arg for the env. It'll be hard to keep it playing through to the end this way, but it's a start.

I will make a version after work this evening, and send you a SynthDef to try out to see if that behavior is better. It might be very doable to keep the .linen, while having holdTime and release interact with one another.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by thresholdpeople** [comment]
Here's another thought. 

The ampEnv is currently the following:

```
var holdTime = (BufFrames.ir(bufnum) * sampleNumChannels - 1) * timeScale;
ampEnv = Env.linen(attack, holdTime, release, 1, ampEnvCurve).kr(Done.freeSelf, gate);
```
timeScale is tsc, and by setting that to 0 in the pattern it gets you the expected behavior. 

```
(
Pdef(0,
	Pbind(*[
		type: \cln,
		snd: \mmd,
		dur: 1/8,
		num: (0 .. 12),
		amp: Pclump(13, Plprand(0.0, 1/59)),
		pan: Pclump(13, Pwhite(0.0, 1.0)),
		tsc: 0,
		rel: Pclump(13, Plprand(0.0, 0.0000000001)),
		crv: Pclump(13, Pwhite(-8.0, 8.0)),
	])
).play
)
```

What do you think about this: having to use an extra parameter to get this sort of behavior?

My other idea is to have rel default to 0 in the SynthDef. Then there would be a boolean expression of some sort that if rel > 0 it would override holdTime to be 0, unless timeScale was also explicitly stated.

The first one works now. The second one is I think a more elegant solution that I think from a user's perspective will 'just work' as expected.

B


‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by thresholdpeople** [comment]
Thinking on it some more, for the second option, nevermind the "just works" -- I think there will be a jump of some sorts. Though it would be closer to the same behavior as when using \clean_envelope. Unless \hld was set explicitly, the samples would get cut short once \atk or \rel were introduced.

**Comment by thresholdpeople** [comment]
Try this updated SynthDef (github doesn't allow scd files, had to compress to a zip).
[TEMP-samplePlayer.scd.zip](https://github.com/danielmkarlsson/SuperClean/files/7460367/TEMP-samplePlayer.scd.zip)
 
and this code:

```

(
Pdef(0,
	Pbind(*[
		type: \cln,
		snd: \mmd,
		dur: 1/8,
		num: (0 .. 12),
		amp: Pclump(13, Plprand(0.0, 1/59)),
		pan: Pclump(13, Pwhite(0.0, 1.0)),
		rel: Pclump(13, Plprand(0.0, 0.0000000001)),
		crv: Pclump(13, Pwhite(-8.0, 8.0)),
		// tsc: 0.2,
		lop: 0,
	])
).play
)
```

Mess with the combo of \tsc and \rel. 

- Without either in the pattern, the sample plays all the way through. 
- With only \rel, the sustain section is dropped. 
- With only \tsc, there is no release time, but the play length gets scaled. 
  - Values greater than one become important with low \freq  or slow \spd settings)
- With both \rel and \tsc, there is a release portion tacked on after the sustain portion

Note that I simplified the SynthDef, adding looping, etc. I believe \lop is set to 1 by default in one of the classes, so for testing purposes of these parameters, it's best to explicitly set \lop to 0, unless you actually want to mess with looping samples.

How do you feel about this interaction?

**Comment by thresholdpeople** [comment]
Sorry for the barrage of messages - there's a strange (to me) thing that happens because of \tsc being used in both the \bnd envelope and the amp envelope.. I think going forward it might be good to separate those to be different..? 
Anyway, just in case you get caught unaware as I just did, just giving you a head's up!

**Pull request merged**
